### ISSUE TITLE
Write migration script to update study fields to support lists

### ISSUE THREAD

**Issue by pcstout** [HBGDki/study-explorer#9]
We need a migration script that can update our currently deployed instances to support the list field without re-importing all the data (ref: https://github.com/HBGDki/study-explorer/issues/5).

**Comment by pcstout** [comment]
@elgertam Any update on this? We will need to the migration soon. Thanks.

**Comment by elgertam** [comment]
This issue is addressed in https://github.com/HBGDki/study-explorer/pull/15.
